spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: demo-no-rate-limiter
          uri: https://httpbin.org/get
          predicates:
            - Path=/no-rate-limiter/**
          filters:
            - RewritePath=/no-rate-limiter(?<segment>.*), /${segment}
        - id: demo-redis-rate-limiter
          uri: https://httpbin.org/get
          predicates:
            - Path=/redis-rate-limiter/**
          filters:
            - RewritePath=/redis-rate-limiter(?<segment>.*), /${segment}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@routeIdKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
